### ISSUE TITLE
sketchlib ran with aa fasta sequences fails unless --concat-fasta is supplied

### ISSUE THREAD

**Issue by tgttunstall** [bacpop/sketchlib.rust#28]
Fails without `--concat-fasta`
```
$ sketchlib sketch -o aa12C_DB --k-vals 3 --seq-files aa_seq*.fasta --seq-type aa -v
2024-10-17T16:02:41.257Z INFO  [sketchlib] Getting input files
2024-10-17T16:02:41.257Z INFO  [sketchlib] Parsed 5 samples in input list
2024-10-17T16:02:41.257Z INFO  [sketchlib] Running sketching: k:[3]; sketch_size:1024; seq:AA(Level1); threads:1
2024-10-17T16:02:41.257Z INFO  [sketchlib::sketch_datafile] Saving sketch data to aa12C_DB.skd
1/5 ████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:0s                        thread '<unnamed>' panicked at src/sketch.rs:266:33:
aa_seq1 has no valid sequence
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2/5 ████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:0s                        thread '<unnamed>' panicked at src/sketch.rs:266:33:
aa_seq2 has no valid sequence
3/5 ████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:0s                        thread '<unnamed>' panicked at src/sketch.rs:266:33:
aa_seq3 has no valid sequence
4/5 ████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░ eta:0s                        thread '<unnamed>' panicked at src/sketch.rs:266:33:
aa_seq4 has no valid sequence
5/5 ████████████████████████████████████████████████████████████████████████████████ eta:0s                        thread '<unnamed>' panicked at src/sketch.rs:266:33:
aa_seq5 has no valid sequence
```
Succeeds with `--concat-fasta`

```
$ sketchlib sketch -o aa12C_DB --k-vals 3 --concat-fasta --seq-files aa_seq*.fasta --seq-type aa -v
2024-10-17T16:02:45.797Z INFO  [sketchlib] Getting input files
2024-10-17T16:02:45.798Z INFO  [sketchlib] Parsed 5 samples in input list
2024-10-17T16:02:45.798Z INFO  [sketchlib] Running sketching: k:[3]; sketch_size:1024; seq:AA(Level1); threads:1
2024-10-17T16:02:45.798Z INFO  [sketchlib::sketch_datafile] Saving sketch data to aa12C_DB.skd
2024-10-17T16:02:45.799Z INFO  [sketchlib::multisketch] Saving sketch metadata to aa12C_DB.skm
2024-10-17T16:02:45.800Z INFO  [sketchlib] Complete
🧬🖋️  sketchlib done in 0s

```

**Comment by johnlees** [comment]
@vrbouza would you be able to help diagnose this?

**Comment by vrbouza** [comment]
Yes, I think I found the bug, #29 fixes the processing of the files @tgttunstall sent me and works as expected after doing a couple tests.
